/* soapSiriConsumerDocBindingService.h
   Generated by gSOAP 2.8.50 for SIRI.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapSiriConsumerDocBindingService_H
#define soapSiriConsumerDocBindingService_H
#include "soapH.h"

    class SOAP_CMAC SiriConsumerDocBindingService {
      public:
        /// Context to manage service IO and data
        struct soap *soap;
        bool soap_own;  ///< flag indicating that this context is owned by this service when context is shared
        /// Variables globally declared in SIRI.h, if any
        /// Construct a service with new managing context
        SiriConsumerDocBindingService();
        /// Copy constructor
        SiriConsumerDocBindingService(const SiriConsumerDocBindingService&);
        /// Construct service given a shared managing context
        SiriConsumerDocBindingService(struct soap*);
        /// Constructor taking input+output mode flags for the new managing context
        SiriConsumerDocBindingService(soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        SiriConsumerDocBindingService(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~SiriConsumerDocBindingService();
        /// Delete all deserialized data (with soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to defaults
        virtual void reset();
        /// Initializer used by constructors
        virtual void SiriConsumerDocBindingService_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual SiriConsumerDocBindingService *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        SiriConsumerDocBindingService& operator=(const SiriConsumerDocBindingService&);
        /// Close connection (normally automatic)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Return sender-related fault to sender
        virtual int soap_senderfault(const char *string, const char *detailXML);
        /// Return sender-related fault with SOAP 1.2 subcode to sender
        virtual int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Return receiver-related fault to sender
        virtual int soap_receiverfault(const char *string, const char *detailXML);
        /// Return receiver-related fault with SOAP 1.2 subcode to sender
        virtual int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
    #ifndef WITH_NOIO
        /// Run simple single-thread (iterative, non-SSL) service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int run(int port);
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// Run simple single-thread SSL service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int ssl_run(int port);
    #endif
        /// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET bind(const char *host, int port, int backlog);
        /// Accept next request (returns socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET accept();
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// When SSL is used, after accept() should perform and accept SSL handshake
        virtual int ssl_accept();
    #endif
    #endif
        /// After accept() serve this request (returns SOAP_OK or error code)
        virtual int serve();
        /// Used by serve() to dispatch a request (returns SOAP_OK or error code)
        virtual int dispatch();
        virtual int dispatch(struct soap *soap);
        ///
        /// Service operations are listed below (you should define these)
        /// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
        ///
        /// Web service one-way operation 'NotifySubscriptionTerminated' (return SOAP_OK (no response) or error code, or use send_NotifySubscriptionTerminated_empty_response())
        virtual int NotifySubscriptionTerminated(ns1__WsSubscriptionTerminatedNotificationStructure *ns1__NotifySubscriptionTerminated) SOAP_PURE_VIRTUAL;
        virtual int send_NotifySubscriptionTerminated_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyDataReady' (return SOAP_OK (no response) or error code, or use send_NotifyDataReady_empty_response())
        virtual int NotifyDataReady(ns1__WsDataReadyNotificationStructure *ns1__NotifyDataReady) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyDataReady_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyHeartbeat' (return SOAP_OK (no response) or error code, or use send_NotifyHeartbeat_empty_response())
        virtual int NotifyHeartbeat(ns1__WsHeartbeatNotificationStructure *ns1__NotifyHeartbeat) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyHeartbeat_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyProductionTimetable' (return SOAP_OK (no response) or error code, or use send_NotifyProductionTimetable_empty_response())
        virtual int NotifyProductionTimetable(ns1__WsProductionTimetableNotificationStructure *ns1__NotifyProductionTimetable) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyProductionTimetable_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyEstimatedTimetable' (return SOAP_OK (no response) or error code, or use send_NotifyEstimatedTimetable_empty_response())
        virtual int NotifyEstimatedTimetable(ns1__WsEstimatedTimetableNotificationStructure *ns1__NotifyEstimatedTimetable) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyEstimatedTimetable_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyStopTimetable' (return SOAP_OK (no response) or error code, or use send_NotifyStopTimetable_empty_response())
        virtual int NotifyStopTimetable(ns1__WsStopTimetableNotificationStructure *ns1__NotifyStopTimetable) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyStopTimetable_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyStopMonitoring' (return SOAP_OK (no response) or error code, or use send_NotifyStopMonitoring_empty_response())
        virtual int NotifyStopMonitoring(ns1__WsStopMonitoringNotificationStructure *ns1__NotifyStopMonitoring) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyStopMonitoring_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyVehicleMonitoring' (return SOAP_OK (no response) or error code, or use send_NotifyVehicleMonitoring_empty_response())
        virtual int NotifyVehicleMonitoring(ns1__WsVehicleMonitoringNotificationStructure *ns1__NotifyVehicleMonitoring) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyVehicleMonitoring_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyConnectionTimetable' (return SOAP_OK (no response) or error code, or use send_NotifyConnectionTimetable_empty_response())
        virtual int NotifyConnectionTimetable(ns1__WsConnectionTimetableNotificationStructure *ns1__NotifyConnectionTimetable) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyConnectionTimetable_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyConnectionMonitoring' (return SOAP_OK (no response) or error code, or use send_NotifyConnectionMonitoring_empty_response())
        virtual int NotifyConnectionMonitoring(ns1__WsConnectionMonitoringNotificationStructure *ns1__NotifyConnectionMonitoring) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyConnectionMonitoring_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyGeneralMessage' (return SOAP_OK (no response) or error code, or use send_NotifyGeneralMessage_empty_response())
        virtual int NotifyGeneralMessage(ns1__WsGeneralMessageNotificationStructure *ns1__NotifyGeneralMessage) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyGeneralMessage_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifyFacilityMonitoring' (return SOAP_OK (no response) or error code, or use send_NotifyFacilityMonitoring_empty_response())
        virtual int NotifyFacilityMonitoring(ns1__WsFacilityMonitoringNotificationStructure *ns1__NotifyFacilityMonitoring) SOAP_PURE_VIRTUAL;
        virtual int send_NotifyFacilityMonitoring_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
        /// Web service one-way operation 'NotifySituationExchange' (return SOAP_OK (no response) or error code, or use send_NotifySituationExchange_empty_response())
        virtual int NotifySituationExchange(ns1__WsSituationExchangeNotificationStructure *ns1__NotifySituationExchange) SOAP_PURE_VIRTUAL;
        virtual int send_NotifySituationExchange_empty_response(int httpcode)
        { return soap_send_empty_response(this->soap, httpcode); }
    };
#endif
